/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  Blog_Building: [
    'Blog_Building/introduction',
    {
      label: 'Hexo',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [

      ],
    },
    {
      label: 'Docusaurus',
      type: 'category',
      link: {
        type: 'doc',
        id: 'Blog_Building/Docusaurus/Docusaurus-guides'
      },
      items: [
        'Blog_Building/Docusaurus/Docusaurus-环境配置',
        'Blog_Building/Docusaurus/Docusaurus-部署',
        'Blog_Building/Docusaurus/Docusaurus-搜索配置',
        'Blog_Building/Docusaurus/Docusaurus-评论服务',
        'Blog_Building/Docusaurus/Docusaurus-图床配置',
      ],
    },
  ],
  skill: [
    'skill/introduction',
    // {
    //   label: 'Docusaurus 主题魔改',
    //   type: 'category',
    //   link: {
    //     type: 'doc',
    //     id: 'skill/docusaurus/docusaurus-guides'
    //   },
    //   items: [
    //     'skill/docusaurus/docusaurus-config',
    //     'skill/docusaurus/docusaurus-style',
    //     'skill/docusaurus/docusaurus-component',
    //     'skill/docusaurus/docusaurus-plugin',
    //     'skill/docusaurus/docusaurus-search',
    //     'skill/docusaurus/docusaurus-comment',
    //     'skill/docusaurus/docusaurus-deploy',
    //   ],
    // },
  ],
  tools: [
    'tools/introduction',
    'tools/everything-quick-search-local-files',
    'tools/wappalyzer-recognize-technology',
    'tools/windows-custom-right-click-menu',
    'tools/vscode-config',
    'tools/idea-config',
    'tools/vite-plugin',
    'tools/jetbrains-product-activation-method',
  ],
  Test: [
    'Test/introduction',
    {
      label: 'Docusaurus 主题魔改111',
      type: 'category',
      link: {
        // type: 'doc',
        // id: 'Test/docusaurus111/docusaurus111-guides',
        title: '主题魔改',
        description: '这里是主题魔改的介绍 然后来一个Github Action部署测试',
        type: 'generated-index',
      },
      items: [
        { 
          type: 'autogenerated',
          dirName: 'Test/docusaurus111',
        },
      ],
    },
  ]
}

module.exports = sidebars
