/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  Blog_Building: [
    'Site/introduction',
    {
      label: 'Hexo',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [

      ],
    },
    {
      label: 'Docusaurus',
      type: 'category',
      link: {
        type: 'doc',
        id: 'Site/Docusaurus/Docusaurus-guides'
      },
      items: [
        'Site/Docusaurus/Docusaurus-环境配置',
        'Site/Docusaurus/Docusaurus-部署',
        'Site/Docusaurus/Docusaurus-样式与页面',
        'Site/Docusaurus/Docusaurus-自定义组件',
        'Site/Docusaurus/Docusaurus-搜索配置',
        'Site/Docusaurus/Docusaurus-评论系统',
        'Site/Docusaurus/Docusaurus-图床配置',
      ],
    },
    {
      label: '网站小技巧',
      type: 'category',
      link: {
        // title: '',
        // description: '记录一些网站的使用小技巧',
        type: 'generated-index',
      },
      items: [
        { 
          type: 'autogenerated',
          dirName: 'Site/Tips',
        },
      ],
    },
  ],
  Stack: [
    'Stack/introduction',
    {
      label: 'C/C++',
      type: 'category',
      link: {
        title: 'C/C++',
        // description: 'C/C++笔记',
        type: 'generated-index',
      },
      items: [
        { 
          type: 'autogenerated',
          dirName: 'Stack/C_C++',
        },
      ],
    },
    {
      label: 'STM32',
      type: 'category',
      link: {
        title: 'STM32',
        // description: 'stm32笔记',
        type: 'generated-index',
      },
      items: [
        { 
          type: 'autogenerated',
          dirName: 'Stack/STM32',
        },
      ],
    },
    {
      label: 'Linux',
      type: 'category',
      link: {
        title: 'Linux',
        // description: 'Linux笔记',
        type: 'generated-index',
      },
      items: [
        { 
          type: 'autogenerated',
          dirName: 'Stack/Linux',
        },
      ],
    },
  ],
  tools: [
    'tools/introduction',
    // 'tools/everything-quick-search-local-files',
    // 'tools/wappalyzer-recognize-technology',
    // 'tools/windows-custom-right-click-menu',
    // 'tools/vscode-config',
    // 'tools/idea-config',
    // 'tools/vite-plugin',
    // 'tools/jetbrains-product-activation-method',
  ],
  Test: [
    'Test/introduction',
    {
      label: 'Docusaurus 主题魔改111',
      type: 'category',
      link: {
        type: 'doc',
        id: 'Test/docusaurus111/docusaurus111-guides',
        // title: '主题魔改',
        // description: '这里是主题魔改的介绍 然后来一个Github Action部署测试',
        // type: 'generated-index',
      },
      items: [
        { 
          type: 'autogenerated',
          dirName: 'Test/docusaurus111',
        },
      ],
    },
  ]
}

module.exports = sidebars
